version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
