version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.20.3
    commands:
      - echo Using Node.js 18.20.3 and npm 10.7.0
      - node -v
      - npm -v
      - npm install -g npm@10.7.0
      - npm -v


  pre_build:
    commands:
      - echo Pre-build phase
      - npm install

  build:
    commands:
      - echo Build phase
      - echo Performing build operations
      - npm run build
      # Add your build commands here

  post_build:
    commands:
      - echo Post-build phase
      - echo Listing all folders again
      # Any additional post-build commands

artifacts:
  files:
    - '**/*'
  discard-paths: no
