version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - #apt install nodejs -y
      - sudo apt update
      - sudo apt install -y curl software-properties-common
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt install -y nodejs
      - npm install


  pre_build:
    commands:
      - echo Pre-build phase
      - npm run build

  build:
    commands:
      - echo Build phase
      - echo Performing build operations
      # Add your build commands here

  post_build:
    commands:
      - echo Post-build phase
      - echo Listing all folders again
      # Any additional post-build commands

artifacts:
  files:
    - '**/*'
  discard-paths: no
